### ISSUE TITLE
Clean up Dynamic Systems Library

### ISSUE THREAD

**Issue by maxchumley** [TeaspoonTDA/teaspoon#86]
There is no way to know the system key for simulation without opening the source code. The system key name should be documented in the PDF that outlines all available systems. 

Some systems also subsample signals without warning so we should warn the user or remove any subsampling.

**Comment by lizliz** [comment]
Agreed! I was just looking into the documentation and realized the same problem. We have the autodocumentation feature, this should be reasonable to add although likely will need a bunch of code annotation cleanup. What's the chance you two wanna take this on @maxchumley @stanweer1 ?

**Comment by lizliz** [comment]
Nevermind, I'm gonna take this on. I'm reorganizing the entire documentation folder structure because of it, but i made a branch (see link to the right) if you want to poke around

**Comment by lizliz** [comment]
Ok, so I just pushed the reorganization of the `doc_source` folder to the branch. I haven't even started getting the DynSysLib autodocumentation working yet, but at least the structure feels more under control. Todos:

- [ ] Actually do the DynSysLib autodocumentation
- [ ] Figure out why the jupyter notebooks aren't rendering. From looking at the live documentation, it appears these have been dead for a while, but they should be put back. Plus it would be excellent to add lots more :D

**Comment by lizliz** [comment]
Ok, now I have a better sense of why this is a problem. @stanweer1 and @maxchumley I have a version of what I think we should do, so I'm hoping you two can go through the rest of the library and do something parallel. 

I have all the rst files set up for DynSysLib and everything is autodocumenting in the branch associated to this issue. In particular, you can see the list of files in the DynSysLib page with the goal of eventually replacing the giant table. <img width="708" alt="image" src="https://github.com/user-attachments/assets/7db65e4a-a8ab-4bf2-ad28-c5ab2dbd6d98">

The problem is that the simulations are inside one giant function in each .py file, so autodocumenting gives us no information. So, your job is to clean up the rest of the files in the folder with the following changes, doing everything in parallel to what I did for the Periodic Functions version. 

- First, extract every system into its own function in the same file. For example, in `periodic_functions.py`, I made a `sine` and `incommensurate_sine` function. Include any additional parameters as the variable inputs (so `omega` if we're following the sine example), and everything should get default values equal to the defaults that would be input if they weren't extracted.
- Make it so that the meta function in each file (called `periodic_functions` in this example) retains its default parameter choices, but does that by calling the system's function instead. 
- Add at least a TODO docstring to everything. My goal would be to extract the contents of [the giant pdf](https://teaspoontda.github.io/teaspoon/_downloads/8d622bebe5abdc608bbc9616ffa444d9/dynamic_systems_library.pdf), so the first part of this job is to figure out where the source code is to generate that. Here's an example in the branch of what I'm going for, although I don't have the figs from the big pdf to add in yet. <img width="708" alt="image" src="https://github.com/user-attachments/assets/1aa83e65-08a4-49da-b56d-f7c869e80f72">
- In the documentation rst file, then separated out the meta function from the rest of the generated stuff. Not sure if that's definitely how we want to do it yet but eventually I'm thinking I'd like to get rid of the meta function system entirely. Perhaps that's for a later date though.

**Comment by lizliz** [comment]
Oops, that shouldn't have closed the issue. It's only partially fixed :D
